SCIENTIFIC_NAMES = {
    'American Redstart': 'Setophaga ruticilla',
    'Bay-breasted Warbler': 'Setophaga castanea',
    'Black-and-white Warbler': 'Mniotilta varia',
    'Black-throated Blue Warbler': 'Setophaga caerulescens',
    'Black-throated Green Warbler': 'Setophaga virens',
    'Blackburnian Warbler': 'Setophaga fusca',
    'Blackpoll Warbler': 'Setophaga striata',
    'Blue-winged Warbler': 'Vermivora cyanoptera',
    'Canada Warbler': 'Cardellina canadensis',
    'Cape May Warbler': 'Setophaga tigrina',
    'Cerulean Warbler': 'Setophaga cerulea',
    'Chestnut-sided Warbler': 'Setophaga pensylvanica',
    'Common Yellowthroat': 'Geothlypis trichas',
    'Connecticut Warbler': 'Oporornis agilis',
    'Golden-winged Warbler': 'Vermivora chrysoptera',
    'Hooded Warbler': 'Setophaga citrina',
    'Kentucky Warbler': 'Geothlypis formosa',
    'Louisiana Waterthrush': 'Parkesia motacilla',
    'Magnolia Warbler': 'Setophaga magnolia',
    'Mourning Warbler': 'Geothlypis philadelphia',
    'Nashville Warbler': 'Leiothlypis ruficapilla',
    'Northern Parula': 'Setophaga americana',
    'Northern Waterthrush': 'Parkesia noveboracensis',
    'Orange-crowned Warbler': 'Leiothlypis celata',
    'Ovenbird': 'Seiurus aurocapilla',
    'Palm Warbler': 'Setophaga palmarum',
    'Pine Warbler': 'Setophaga pinus',
    'Prairie Warbler': 'Setophaga discolor',
    'Prothonotary Warbler': 'Protonotaria citrea',
    'Tennessee Warbler': 'Leiothlypis peregrina',
    "Wilson's Warbler": 'Cardellina pusilla',
    'Worm-eating Warbler': 'Helmitheros vermivorum',
    'Yellow Warbler': 'Setophaga petechia',
    'Yellow-rumped Warbler': 'Setophaga coronata',
    'Yellow-throated Warbler': 'Setophaga dominica',
} 